### PR TITLE
Thumb approximation for Index Emulation

### PR DESCRIPTION
**Pull request by lucas-vrtech**
Allow some degree of thumb motion in index-emulated games, by setting (capacitive) touch on the A button when the thumb is pushed beyond a certain threshold.

### CODE REVIEW

**Review by danwillm — COMMENTED** [review]
I feel like this kind of thing should be within the firmware - thoughts?

**Comment by TwidgeVR** [comment]
firmware doesn't currently have a label for this 'touching a button' value but it would be nice for folks who might want to turn it off for some reason, however needs a change both places in that case.  this may be easier if always using this gestural behavior is going to be generally preferrable

**Comment by lucas-vrtech** [comment]
Yeah, I think this was a bit of a misunderstanding caused by a typo I had in the code. The only purpose for doing this is specifically for the render model of hands to sort of show the thumb moving in index emulation-only games, so I can't think of any situation where it would be favorable for the firmware to have control over this.

**Review by danwillm — APPROVED** [review]
Cool, if you want to add it as a setting in this pr, then do, or merge and we can add it in later.

**Review by danwillm — APPROVED** [review]
👍 
Might also want to add a description string and title into the ui for this option?
https://github.com/LucidVR/opengloves-ui/blob/main/src/strings/configuration_options.json

**Comment by lucas-vrtech** [comment]
Sure, will do

**Pull request merged**
