### PR TITLE
Remove add to steam step

### PR DESCRIPTION
**Pull request by danwillm**
The process to link the driver with steamvr is covered in the following sections

### CODE REVIEW

**Review by lucas-vrtech — CHANGES_REQUESTED** [review]
I think this is still an important step to document, for those that are not actively using the debugger. It is also useful for testing release builds without adding to openvrpaths. Maybe instead of removing, it would be better to specify that this step is not required for anyone who modified openvrpaths.

**Comment by danwillm** [comment]
> 
> 
> I think this is still an important step to document, for those that are not actively using the debugger. It is also useful for testing release builds without adding to openvrpaths. Maybe instead of removing, it would be better to specify that this step is not required for anyone who modified openvrpaths.

Fair enough - I added it back but added a small note in that step for extra clarification.

**Review by lucas-vrtech — CHANGES_REQUESTED** [review]
Aside from that, looks great

**Review by lucas-vrtech — APPROVED** [review]
👍

**Comment by danwillm** [comment]
🚀

**Pull request merged**
